Repository line/line-bot-sdk-java, pull requests merged in 2019-12, with the labels that each got.

#404 NON-ISSUE Reformat file.
  line-bot-model/src/main/java/com/linecorp/bot/model/event/JoinEvent.java
Labels: trivial

#409 NON-ISSUE Refactoring sample-spring-boot
  sample-spring-boot-echo-kotlin/build.gradle
  sample-spring-boot-echo-kotlin/src/main/kotlin/com/example/bot/spring/echo/EchoApplication.kt
  sample-spring-boot-echo/build.gradle
  sample-spring-boot-echo/src/main/java/com/example/bot/spring/echo/EchoApplication.java
Labels: enhancement

#422 modify http method of v2/bot/richmenu/bulk/unlink
  line-bot-api-client/src/main/java/com/linecorp/bot/client/LineMessagingService.java
Labels: bug

#416 Support notificationDisabled option for Multicast, PushMessage, ReplyMessage
  line-bot-api-client/src/test/java/com/linecorp/bot/client/LineMessagingClientImplIntegrationTest.java
  line-bot-api-client/src/test/java/com/linecorp/bot/client/LineMessagingClientImplTest.java
  line-bot-model/src/main/java/com/linecorp/bot/model/Broadcast.java
  line-bot-model/src/main/java/com/linecorp/bot/model/Multicast.java
  line-bot-model/src/main/java/com/linecorp/bot/model/PushMessage.java
  line-bot-model/src/main/java/com/linecorp/bot/model/ReplyMessage.java
  line-bot-model/src/test/java/com/linecorp/bot/model/message/MessageJsonReconstructionTest.java
  line-bot-spring-boot/src/test/java/com/linecorp/bot/spring/boot/IntegrationTest.java
  sample-spring-boot-kitchensink/src/main/java/com/example/bot/spring/KitchenSinkController.java
Labels: enhancement, new feature
