Repository line/line-bot-sdk-java, pull requests merged in 2020-05, with the labels that each got.

#517 Upgrade gradle-lombok plugin to 4.0.0
  build.gradle
Labels: dependency change

#508 Support Channel access token v2.1
  build.gradle
  line-bot-api-client/build.gradle
  line-bot-api-client/src/integrationTest/java/com/linecorp/bot/client/IntegrationTestSettingsLoader.java
  line-bot-api-client/src/integrationTest/java/com/linecorp/bot/client/LineOAuthClientIntegrationTest.java
  line-bot-api-client/src/main/java/com/linecorp/bot/client/LineOAuthClient.java
  line-bot-api-client/src/main/java/com/linecorp/bot/client/LineOAuthClientImpl.java
  line-bot-api-client/src/main/java/com/linecorp/bot/client/LineOAuthService.java
Labels: new feature

#527 Update LineBlobClient.java Fix typo. s/blog/blob/
  line-bot-api-client/src/main/java/com/linecorp/bot/client/LineBlobClient.java
Labels: CI/CD/Documentation
