Repository line/line-bot-sdk-java, pull requests merged in 2021-07, with the labels that each got.

#653 Support RichMenuAlias APIs and RichMenuSwitchAction
  line-bot-api-client/src/main/java/com/linecorp/bot/client/LineMessagingClient.java
  line-bot-api-client/src/main/java/com/linecorp/bot/client/LineMessagingClientImpl.java
  line-bot-api-client/src/main/java/com/linecorp/bot/client/LineMessagingService.java
  line-bot-api-client/src/test/java/com/linecorp/bot/client/LineMessagingClientImplTest.java
  line-bot-model/src/main/java/com/linecorp/bot/model/action/RichMenuSwitchAction.java
  line-bot-model/src/main/java/com/linecorp/bot/model/richmenualias/CreateRichMenuAliasRequest.java
  line-bot-model/src/main/java/com/linecorp/bot/model/richmenualias/RichMenuAliasListResponse.java
  line-bot-model/src/main/java/com/linecorp/bot/model/richmenualias/RichMenuAliasResponse.java
  line-bot-model/src/main/java/com/linecorp/bot/model/richmenualias/UpdateRichMenuAliasRequest.java
Labels: new feature

#665 Add @JsonInclude annotation to audiences field
  line-bot-model/src/main/java/com/linecorp/bot/model/manageaudience/request/CreateAudienceGroupRequest.java
Labels: bug

#669 Upgrade to spring boot from 2.3.5.RELEASE to 2.4.9
  build.gradle
  line-bot-api-client/build.gradle
Labels: dependency change

#671 Upgrade gradle from 6.7.1 to 6.8.3
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependency change

#672 Bump Spring boot from 2.4.9 to 2.5.3
  build.gradle
Labels: dependency change
